# Generated by Django 3.2.7 on 2021-09-28 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conferenceroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('places', models.IntegerField()),
                ('projector', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
                ('comment', models.CharField(max_length=255)),
                ('cfroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cfrooms_reservation.conferenceroom')),
            ],
        ),
    ]
