# Generated by Django 3.2.7 on 2021-10-02 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cfrooms_reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='cfroom_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cfrooms_reservation.conferenceroom'),
        ),
    ]
