# Generated by Django 3.2.7 on 2021-10-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cfrooms_reservation', '0002_alter_reservation_cfroom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceroom',
            name='places',
            field=models.IntegerField(default=0),
        ),
    ]
